# we want to make sure it is run on trusty where sudo is provided for postgres
dist: xenial
language: python
python:
    - "3.7"
sudo: required
env:
  - DATABASE=DUMMY
services:
  - redis-server
  - docker

install:
  - pip install -e .[test]
  - pip install flake8 codecov
  - sleep 5
script:
  - flake8 guillotina_amqp --config=setup.cfg
  - pytest -s --cov=guillotina_amqp -s --tb=native -v --cov-report term-missing --cov-append guillotina_amqp
after_success:
  - codecov
