name: guillotina_amqp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      # Checkout the repo first
      - uses: actions/checkout@v2

      # Setup the python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies

      # Linters
      - name: Lint with flake8
        run: |
          # Install flake8
          pip install flake8

          # Run it
          flake8 guillotina_amqp --config=setup.cfg

      # Run tests
      - name: Run tests
        run: |
          # Install package with test dependecies
          pip install -e .[test]
          pytest --capture=no --tb=native -v guillotina_amqp
